const ALBUM_TYPES = {
    FETCH_ALBUM_START: "FETCH_ALBUM_START",
    FETCH_ALBUM_SUCCESS: "FETCH_ALBUM_SUCCESS",
    FETCH_ALBUM_FAILURE: "FETCH_ALBUM_FAILURE",
    FILTER_ALBUM: "FILTER_ALBUM"
}

export default ALBUM_TYPES